/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cristogamescliente;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Label;
import java.awt.Panel;
import java.util.List;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author hanokme
 */
public class VentanaJuego extends javax.swing.JFrame {

    
    private final ControladorCliente controlador;
    private JPanel panelResenias;
    public int idJuego;

    public VentanaJuego(ControladorCliente controlador, Map<String, Object> datosJuego) {
        this.controlador = controlador;
        this.idJuego = (int) datosJuego.get("idJuego");
        initComponents();
        configurarScrollPane();
        cargarDatosJuego(datosJuego);
    }

    private void configurarScrollPane() {
        // Crear y configurar el panel que contendrá las reseñas
        panelResenias = new JPanel();
        panelResenias.setLayout(new BoxLayout(panelResenias, BoxLayout.Y_AXIS));

        // Asignar el panel al JScrollPane
        jScrollPaneResenias.setViewportView(panelResenias);
    }

    private void cargarDatosJuego(Map<String, Object> datosJuego) {

        if (datosJuego == null) {
            System.out.println("❌No se pudo obtener la información del juego.");
            return;
        }

        jLabelTitulo.setText((String) datosJuego.get("nombre"));
        jLabelEstudio.setText("Estudio: " + datosJuego.get("estudio"));
        jLabelLanzamiento.setText("Lanzamiento: " + datosJuego.get("lanzamiento"));
        jLabelGenero.setText("Género: " + datosJuego.get("genero"));
        jLabelCalificacion.setText("Calificación: " + datosJuego.get("calificacion"));

        actualizarResenias(datosJuego);

    }
    
    public void actualizarResenias(Map<String, Object> datosJuego) {
        SwingUtilities.invokeLater(() -> {
            panelResenias.removeAll();
            List<Map<String, String>> resenias = (List<Map<String, String>>) datosJuego.get("resenias");
            System.out.println("🔄Resenias obtenidas para la actualización: " + resenias);

            for (Map<String, String> resenia : resenias) {
                JPanel reseniaPanel = new JPanel();
                reseniaPanel.setLayout(new FlowLayout(FlowLayout.LEFT));
                reseniaPanel.setBorder(BorderFactory.createLineBorder(Color.GRAY));
                reseniaPanel.setBackground(Color.LIGHT_GRAY);
                reseniaPanel.setPreferredSize(new Dimension(380, 70));

                JLabel lblResenia = new JLabel("<html><b>" + resenia.get("username") + "</b> ("
                        + resenia.get("fecha") + "):<br>"
                        + resenia.get("texto") + " ⭐" + resenia.get("calificacion") + "</html>");

                reseniaPanel.add(lblResenia);
                panelResenias.add(reseniaPanel);
            }

            panelResenias.revalidate();
            panelResenias.repaint();
        });
    }
    
    public void recargarDatosJuego(){
        SwingUtilities.invokeLater(() -> {
            System.out.println("🔄Recargando datos del juego en la interfaz...");
            Map<String, Object> datosJuego = controlador.solicitarInfoJuego(idJuego);
            if (datosJuego != null) {
                Object nuevaCalificacion = datosJuego.get("calificacion");
                jLabelCalificacion.setText("Calificación: " + nuevaCalificacion);
                actualizarResenias(datosJuego);
                jScrollPaneResenias.revalidate();
                jScrollPaneResenias.repaint();
                getContentPane().invalidate();
                getContentPane().validate();
                getContentPane().repaint();
            } else {
                System.err.println("❌No se pudo actualizar la información del juego.");
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSuperiorDetallesJuego = new javax.swing.JPanel();
        jButtonAtras = new javax.swing.JButton();
        jPanelImagenVideojuego = new javax.swing.JPanel();
        jPanelDetallesJuego = new javax.swing.JPanel();
        jLabelEstudio = new javax.swing.JLabel();
        jLabelLanzamiento = new javax.swing.JLabel();
        jLabelGenero = new javax.swing.JLabel();
        jLabelCalificacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonJugar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPaneResenias = new javax.swing.JScrollPane();
        jButtonResenia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSuperiorDetallesJuego.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonAtras.setText("Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSuperiorDetallesJuegoLayout = new javax.swing.GroupLayout(jPanelSuperiorDetallesJuego);
        jPanelSuperiorDetallesJuego.setLayout(jPanelSuperiorDetallesJuegoLayout);
        jPanelSuperiorDetallesJuegoLayout.setHorizontalGroup(
            jPanelSuperiorDetallesJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorDetallesJuegoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButtonAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSuperiorDetallesJuegoLayout.setVerticalGroup(
            jPanelSuperiorDetallesJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorDetallesJuegoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanelImagenVideojuego.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelImagenVideojuegoLayout = new javax.swing.GroupLayout(jPanelImagenVideojuego);
        jPanelImagenVideojuego.setLayout(jPanelImagenVideojuegoLayout);
        jPanelImagenVideojuegoLayout.setHorizontalGroup(
            jPanelImagenVideojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );
        jPanelImagenVideojuegoLayout.setVerticalGroup(
            jPanelImagenVideojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelDetallesJuego.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelEstudio.setText("jLabel2");

        jLabelLanzamiento.setText("jLabel2");

        jLabelGenero.setText("jLabel2");

        jLabelCalificacion.setText("jLabel2");

        javax.swing.GroupLayout jPanelDetallesJuegoLayout = new javax.swing.GroupLayout(jPanelDetallesJuego);
        jPanelDetallesJuego.setLayout(jPanelDetallesJuegoLayout);
        jPanelDetallesJuegoLayout.setHorizontalGroup(
            jPanelDetallesJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetallesJuegoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelDetallesJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCalificacion)
                    .addComponent(jLabelGenero)
                    .addComponent(jLabelLanzamiento)
                    .addComponent(jLabelEstudio))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        jPanelDetallesJuegoLayout.setVerticalGroup(
            jPanelDetallesJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetallesJuegoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelEstudio)
                .addGap(28, 28, 28)
                .addComponent(jLabelLanzamiento)
                .addGap(36, 36, 36)
                .addComponent(jLabelGenero)
                .addGap(37, 37, 37)
                .addComponent(jLabelCalificacion)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jLabel1.setText("Detalles del videojuegos");

        jButtonJugar.setText("Jugar");

        jLabelTitulo.setText("Titulo");

        jButtonResenia.setText("Valorar");
        jButtonResenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReseniaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSuperiorDetallesJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelImagenVideojuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneResenias, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDetallesJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonResenia)
                            .addComponent(jButtonJugar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelSuperiorDetallesJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelTitulo))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelImagenVideojuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDetallesJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneResenias, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButtonJugar)
                        .addGap(69, 69, 69)
                        .addComponent(jButtonResenia)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonReseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReseniaActionPerformed
        controlador.mostrarVentanaResenia(idJuego);
    }//GEN-LAST:event_jButtonReseniaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JButton jButtonResenia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCalificacion;
    private javax.swing.JLabel jLabelEstudio;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelLanzamiento;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelDetallesJuego;
    private javax.swing.JPanel jPanelImagenVideojuego;
    private javax.swing.JPanel jPanelSuperiorDetallesJuego;
    private javax.swing.JScrollPane jScrollPaneResenias;
    // End of variables declaration//GEN-END:variables
}
